//export const URL_BACK_AUTHENTICATE = '/authenticate'
export const URL_BACK_AUTHENTICATE = '/auth/login'
export const URL_BACK_REGISTER = 'auth/register'
export const URL_BACK_ACCOUNT = '/users'
//export const URL_BACK_AUTHENTICATE = '/users'