//juste les nom des urls
export const URL_HOME = '/'
export const URL_LOGIN = '/login'
export const URL_REGISTER = '/register'
export const URL_ADMIN_HOME = '/admin'

export const URL_BOUTIQUE = '/boutique'
export const URL_DETAIL = '/detail'
export const URL_PANIER = '/panier'
export const URL_ENVIE = '/listeenvies'
export const URL_PRESENTATION = '/presentation'

export const URL_FORGOTPASSWORD = '/forgot-password'
export const URL_CGU = '/cgu'
export const URL_CONTACT = '/contact'
export const URL_MENTIONS = '/mentions-legales'
export const URL_PAIEMENT = '/paiement'
export const URL_LIVRAISON_RETOUR = '/livraison-retour'

export const URL_INFO_PERSO = '/compte/informations-personnelles'
export const URL_RETOUR_PRODUIT = '/compte/retour-produit'
export const URL_COMMANDE = '/compte/commande'
export const URL_ADRESSE = '/compte/adresse'

export const URL_CONTACT_FORM = '/contactForm'
export const URL_LIVRAISON = '/livraison'
export const URL_LISTEENVIES = '/listeenvies'
export const URL_TICKET = '/ticket'
export const URL_VALIDATION = '/validation'
export const URL_CLAIM = '/claim'
export const URL_ACCOUNT = '/account'
